### ISSUE TITLE
Přechod na premium 3

### ISSUE THREAD

**Issue by druli** [mtester270/archivczskpremium#10]
Po instalaci a odsouhlasení "premium" jak se smazáním, tak bez chyba:

Některý z modulů není dostupný :
Extension/archivCZSKpremium (/usr/lib/python2.7/site-packages/Crypto/Util/_sounter.so: Cannot open shared object file: No such file or directory)

**Comment by mtester270** [comment]
Treba vam viac citat pred tym ako zakladate issue.

https://github.com/mtester270/archivczskpremium/releases/tag/v1.0.0
