### ISSUE TITLE
archivczskpremium poplatek

### ISSUE THREAD

**Issue by klubru** [mtester270/archivczskpremium#11]
Poplatek jsem odeslal již 2x a stále není provedena aktivace.
![1_0_19_3395_C89_3_EB0000_0_0_0](https://user-images.githubusercontent.com/34919011/58371043-1d56ac80-7f0e-11e9-9b43-2131a5ef918e.jpg)
![platba](https://user-images.githubusercontent.com/34919011/58371044-1def4300-7f0e-11e9-8c3f-d25a3ecc5c62.jpg)

**Comment by hansolo272** [comment]
hm jaksi podivná platba ?
a tohle na github issues nepatrí !
proč var symbol a proč specific symbol ?
kde máš ident platby ?
co provádiš na paypal netuším 
ale v emeilu prevodu paypal vidno normálne 
Aktualizácia SW  
Identifikacia platby: xx ident kod xx | €1,20 EUR
 a vše jde bez problému

**Comment by mtester270** [comment]
Po zaplateni musi byt platba este spracovana platba manualne. Kedze som mimo PC tak budem riesit dnes podvecer. Dakujem za pochopenie.
