### ISSUE TITLE
Zamrznutie po spustení vyhľadávania

### ISSUE THREAD

**Issue by dzupo** [mtester270/archivczskpremium#12]
Keď spustím vyhľadávanie v Stream Cinema, tak nemôžem nič písať a už ani odísť z menu vyhľadávania. Nereaguje žiadne tlačidlo na DO. Prijímač ale na pozadí ide ďalej. Musím ho reštartovať cez web rozhranie.
Archivczsk premium 1.0.1
VU+ Uno 4k SE - openatv 6.2

**Comment by hansolo272** [comment]
aktuálne venku verze 1.0.2
pokud problém trvá , chtelo by to log 
crashlog atd ,muže bít problém v phyton openatv
nebo v skinu
nebo
virtual keyboard atd 
u 1.0.1 žádný problém nevidím v Image VTI 14.0.3
skin atilehd + hdglass16
čekám na aktualizaci online na 1.0.2

**Comment by dzupo** [comment]
Crashlog prijímač neulozi. Ako dostanem log?

**Comment by hansolo272** [comment]
up na verzi 
1.0.2 taky bez problému vyhledávání 
jak doplnkem nebo dlouhé tlač epg !
v nastavení premium /4 strana dej logováni ano 
pak cesta total comander  / tmp /archiv_logs 

videl bych to ovšem u tebe na chybu skinu nebo image 
doplnek premium 1.0.1/1.0.2 test ok

**Comment by mtester270** [comment]
Odporucam zmenit image na VTi. OpenAtv ma vacne problemy. Pre identifikaciu treba v nastaveniach zapnut Detailne logovanie potom navodit situaciu a poslat logy z uz spominanej zlozky. Inac nepomozem.

**Comment by dzupo** [comment]
Tu je log:
[archivCZSKpremium.log](https://github.com/mtester270/archivczskpremium/files/3228795/archivCZSKpremium.log)

**Comment by hansolo272** [comment]
samé cannot !
18:44:18.424 [DEBUG] Opening item '<PSearch - [B]Vyhladat[/B]>'...
18:44:18.478 [DEBUG] CustomImporter 'plugin.video.stream-cinema' import 'sys' (path=None) ...
18:44:18.480 [DEBUG] CustomImporter 'plugin.video.stream-cinema' cannot found modul 'sys'
18:44:18.482 [DEBUG] CustomImporter 'script.module.stream.resolver' import 'sys' (path=None) ...
18:44:18.484 [DEBUG] CustomImporter 'script.module.stream.resolver' cannot found modul 'sys'
atd

hm hm hm 
skus /6.1/ 6.3  openatv pokud nejede 6.2
pak už jen zmena image bohužel na stabilnejší ne otevrené 
plugin jede bez problému

**Comment by dzupo** [comment]
Ako je to s existujucim predplatnym po preinstalovani image?

**Comment by mtester270** [comment]
Si si isty ze si spustil vyhladavanie zamrzlo ti to a potom si skopiroval log? Ak ano tak v logu nie je ziadna chyba a kedze nevlastnim tvoj pristroj tak ti doporucim zmenit image na VTi tam by malo vsetko fungovat.

**Comment by dzupo** [comment]
Ano, presne takto som to spravil.
Okrem toho, obrazovka vyhladavania vyzera nestandartne, myslim.
![2019-05-28 20_02_48-Window](https://user-images.githubusercontent.com/51127437/58500984-a6c2e480-8183-11e9-9de4-29ad912b95d5.jpg)

**Comment by mtester270** [comment]
Skuste iny image alebo mozno verziu atv6.3. Nemam vam ako pomoct.

**Comment by dzupo** [comment]
ok
