### ISSUE TITLE
zamŕzanie po ukončení prehrávania niektorých seriálov

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#13]
Ahoj,

pri seriáli Oteckovia mi po ukončení zamrzne archív tak, že pomôže len tvrdý reštart. Po skončení dielu sa normálne prepne do menu seriálu a koniec. Diaľkové už na nič nereaguje a na pozadí satelitný tuner funguje. Po ukončení iných seriálov sa trakt normálne spáruje a je to OK. 
Mám VTI 13.0.9., VU+ UNO SK SE.
Predpokladám opätovný problém s traktom, ale môžem sa mýliť, pretože pred cca. týždňom to ešte nerobilo.
Môžeš na to mrknúť v čom to bude?

ďakujem
Tu je výpis z logu:
19:02:06.039 [ERROR] getPosterImage failed (return no image).
Traceback (most recent call last):
  File ".\gui\content.py", line 560, in getPosterImage
  File ".\engine\tools\util.py", line 152, in download_web_file
  File "/usr/lib/python2.7/urllib2.py", line 155, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 424, in open
    protocol = req.get_type()
  File "/usr/lib/python2.7/urllib2.py", line 286, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: None

**Comment by mtester270** [comment]
Robi to za kazdym ci len obcas? Lebo ak obcas tak o jednom probleme viem ale kedze nastava len obcas tak ho mam stale v rieseni. Kazdopadne potrebujem vidiet cely log!!!

Poprosim prilozit cely log adresar a taktiez poprosim zapnut detailne logovanie v nastaveniach asi 3 zalozka.

**Comment by gladius70** [comment]
Pri Oteckoch to robí vždy. Toto bol celý log adresár, nič iné tam nebolo. 
Teraz som zapol detailné logovanie a pokúsim sa to nasimulovať ešte raz. Potom to dám detailný log..

**Comment by gladius70** [comment]
Ešte doplním, že do minulého týždňa to pri Oteckoch robilo len občas, ale naposledy to spárovalo s traktom v utorok a od utorka to mrzne vždy.

**Comment by gladius70** [comment]
Ja to kašlem. Týždeň to mrzne a po zapnutí detailného logu dnes všetko bez problémov. 
Myslím, že to môžeme zavrieť , o probléme vieš a keď sa to znova objaví, pošlem detailný log.

**Comment by mtester270** [comment]
tak to bude presne ten co som pisal raz to pada inokedy to funguje. S traktom to nebude, zatial com som vykumal je to problem na systemovej urovne kde nieco zblbne a zrazu nechce naimportovat 'sys' ak ti to nieco hovori tak ti je jasne ze sa to hned zdrbe ked to nema 'import sys'. Zatial som neprisiel na to co to sposobuje a podla vsetkeho to robilo aj v starom archive ale pracujem na nejakom work-around.

**Comment by mtester270** [comment]
tak opravene, akurat som spravil workaround ktory funguje.

Bude v dalsej aktualizacii + par dalsich veci :)
