### ISSUE TITLE
supportOE2.6

### ISSUE THREAD

**Issue by forsajd** [mtester270/archivczskpremium#14]
skusam nainstalovat archiv do dreamboxone len sa mi nedari subssupport nainstalobat samotny archiv som nainstaloval len pyta aj subssupport da sa ti to urobit aj na supportOE2.6

**Comment by forsajd** [comment]
zobralo to z iného zdroja aj OE2.5

**Comment by mtester270** [comment]
neviem co si instaloval ale archiv premium subssupport nemoze vyzadovat :)

**Comment by forsajd** [comment]
takto aby si vedel ako: mam dreamboxone na test do ktoreho skoro nic nie je z verzii OS2.5 lebo pouziva OS2.6, jedine co sa mi z archivu podarilo naistalovat je archivczsk_1.2.2-20190505.deb a tam mi po instalovani  pytal subssupport, tvoju verziu ani neslo nainstalovat : ipkg -i https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/python-pycrypto_2.5-r0.4_armhf.1.deb a ani  subssupport : dpkg -i http://github.com/mx3L/archivczsk/releases/download/v1.0/enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb

**Comment by mtester270** [comment]
Tak to fakt neviem co si instaloval lebo kazdy link co si tu dal nie je premium verzia. Staru verziu tu nemotaj stym uz nemam nic spolocne a ziadny support k nej neposkytujem. Pokial nieco nejde naistalovat tak potrebujem vidiet logy a to myslim logy consoly alebo co vypise po spustenii premium verzie. Subssuport nie je moj plugin a teda k tomu podporu tiez neposkytujem treba popozerat po internete novsiu verziu ci pojde.

**Comment by forsajd** [comment]
len tvoja verzia nejde https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/python-pycrypto_2.5-r0.4_armhf.1.deb a ostane ipk do dreamboxuone nedas potrebujem deb nie ipk jeni na ktora sla nainstalovat je co nie je premium a to táto http://github.com/mx3L/archivczsk/releases/download/v1.0/enigma2-plugin-extensions-subssupport_OE2.5_1.5.6-r0.2_all.deb
