### ISSUE TITLE
Crash while press "OK" in Virtual Keyboard

### ISSUE THREAD

**Issue by petrkr** [mtester270/archivczskpremium#18]
Same bug as in standard version. Fixed by https://github.com/petrkr/archivczsk/commit/81f1da88b6e0e6c0ec204f826991066d8d343d9f this change.

**Comment by mtester270** [comment]
Skuste prepisat prilozeny subor a dajte vediet ci to uz funguje. Ak ano tak to bude v dalsej verzii.

[archivCZSKpremium.zip](https://github.com/mtester270/archivczskpremium/files/3642002/archivCZSKpremium.zip)

**Comment by petrkr** [comment]
Vypada to na prvni test v poradku

![1_0_1_1F43_CA1_3_EB0000_0_0_0_20190923180439](https://user-images.githubusercontent.com/6428351/65442592-bcdc6b00-de2c-11e9-9034-dd1f420188ea.jpg)

![1_0_1_1F43_CA1_3_EB0000_0_0_0_20190923180450](https://user-images.githubusercontent.com/6428351/65442590-bcdc6b00-de2c-11e9-874c-d92290fe78a0.jpg)

**Comment by mtester270** [comment]
"prvni test"? Tak to asi dotestujte uplne a tak mi dajte vediet.

**Comment by petrkr** [comment]
Mysleno je, ze sem to zkusil, funguje, zatim nemam jinej test v planu. Za me dobry. Lepsi jak modra smrt, kterou to hazelo predtim.

**Comment by petrkr** [comment]
a nevim proc neslo dat "comment" aniz bych udelal "close"
