### ISSUE TITLE
Podivne chovani o2tv

### ISSUE THREAD

**Issue by petrkr** [mtester270/archivczskpremium#19]
V pripade O2TV se vysila m3u8 seznam po 10sec segmentech. Vypada to, ze plugin nejak spatne tyto segmenty spojuje, protoze se kazdych cca 10sec obraz "prsekne" a pak se jakoze zrychli aby "stihnul" dohrat zbytek segmentu... Zkouseno vice Image i vice satelitnich prijimacu. o2tv na oficielnim webu ani mobilni aplikaci takoveto chovani nedela.

Muzu nabidnout nejakou soucinnost pri ladeni tohoto problemu.

**Comment by mtester270** [comment]
Skusit nieco mozes ale to co popisujes je skor vecou enigmy (resp. prehravaca) a nie pluginu a to bol jeden z hlavnych dovodov preco som pridal moznost zvolit si prehravac.

Skusal si to aj v inych prehravacoch na roznych image (vid nastavenie doplnku)?

**Comment by petrkr** [comment]
Cece zkousel a dokonce to dela i v PC ve vlc, ale nasel sem nejakej workaround pro dash streamy prohnat se skrz ffmpeg, zkusim to najit a mozna by to slo do pluginu dorvat nejak... problem je ze tem part (10sec) streamuj neco chybi ci prebejva a ten prehtavac pak ztraci (resp duplikuje) snimky a apak se to chova takhle divne.

Az budu na pc zkusim poslat command z ffmpegu, bohuzel v mem inage je ffmpeg verze 3x a ten jeste DASH neumi :(

**Comment by petrkr** [comment]
Zkousel jsem ruzne webove prehravace (javascript) pro ten DASH a zjistil jsem, ze nektere delaji totez co engima2 (a plugin o2tv) a jeden ne. Zaroven sem si vsimnul, ze ten co funguje nacita aktualni cas ze serveru o2. Mozna by to souviselo.

Tento nefunguje: https://bitmovin.com/demos/stream-test?format=dash
Tento funguje: https://developer.jwplayer.com/tools/stream-tester/

presto oba budou pouzivat stejny dekoder v prohlizeci. Jde o pripravu dat pro tento dekoder.

Tj stejne jako plugin by to mohl nejak "predchroupat" pro ten enigma2 (pravdepodobne gstreamer?)

**Comment by mtester270** [comment]
Z vacsej miery netusim co s tym by som mohol spravit resp. ako by som nastavil nieco ako cas pre e2 player etc. gstreamer

**Comment by petrkr** [comment]
Prinejmensim tam mate nekde vyparzovany zakladni API, kterym se da dostat az k URL toho streamu. Dal bych si s tim mohl zkusit pohrat, pro zacatek zkusit ten ffmpeg "workaround", kterej by to mohl predzvejkat. Blby je, ze se nedostanu k tomu pluginu. Zaroven je trosku blby, ze ffmpeg je uz velkej "moloch" a neni to v ramci pythonu, a kazdej satelit ma jinej procesor a vyzadovalo by to mit binarni verzi ffmpeg pro vetsinu z nich.

Zkusim v mezicase nejak nastudovat jak predhodit enigma2 z nejakeho addonu podmet k prehravani streamu (nevim jestli toje neco jako v androidu, ze zavolam jakejsi interni dekoder). A zkusil bych udelat nejakej example

**Comment by mtester270** [comment]
Nie celkom som pochopil ale pokial hladas url na stream tak staci na E2 spustit stream cez plugin nasledne ist cez browser na IP pristroja zvolit zalozku "teraz" a tam si to staci vykopirovat. Pokial som nepochopil tak sa skus pytat konretnejsie.

**Comment by mtester270** [comment]
Kedze si stym asi nepohol a aj keby tak archiv stym nic nespravi, takze zatvaram ak cosi tak to ti potom kludne otvorim.
