### ISSUE TITLE
prechod na premium

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#2]
Ahoj,

bude sa dať aktualizovať archív na premium verziu aj po odkliknutí nie?
Alebo ho bude nutné preinštalovať cez telnet?

S príspevkom nemám problém, len musím vedieť za čo platím a bohužiaľ ho nemôžem vyskúšať pretože obyvateľstvo domácnosti bolo rýchlejšie ako ja.

**Comment by mtester270** [comment]
Bud cez instalaciu IPK balicku alebo ak chces znova vidiet prechod na premium tak treba vymazat adresar
/usr/lib/enigma2/python/Plugins/Extensions/archivCZSKpremium/
