### ISSUE TITLE
Archiv cz sk premium - RTVS

### ISSUE THREAD

**Issue by papopp** [mtester270/archivczskpremium#21]
Zdravim, ked spustim doplnok rtvs.sk_zive vysielanie_STV1 tak sa mi zobrazi hlaska ( foto ). Archiv bol aktualizvany cca pred mesiacom za poplatok. Je to mozne nejako vyriesit. Este sa opytam ak si teraz aktualizujem cely archiv, budu tam zahrnute vsetky aktualizacie k datumu 27.10.2019? Dakujem za odpoved.
![1](https://user-images.githubusercontent.com/57176384/67849662-460b4f80-fb07-11e9-8780-fe4e6a53085f.jpg)
![2](https://user-images.githubusercontent.com/57176384/67849680-4ad00380-fb07-11e9-8b3f-b59afd4a5cda.jpg)

**Comment by mtester270** [comment]
Ano budu.
Live prenos pozriem ak to bud emozne opravim a bude v dalsom release.

**Comment by mtester270** [comment]
Pokial chcete opravu uz teraz da sa spravit update len pre vas za klasicky poplatok. V pripade zaujmu napiste email.

**Comment by papopp** [comment]
Prosil by som opravu ( update ) len pre mna. Napiste ako postupovat s platbou. Dakujem

**Comment by mtester270** [comment]
Napiste mi mail, potom poslem instrukcie.

http://chaossevn.aspifyhost.cz/archiv
