### ISSUE TITLE
nefunkčný archivczskpremium

### ISSUE THREAD

**Issue by joseph1421** [mtester270/archivczskpremium#23]
prosím o radu, nejde mi archivczskpremium, po spustení naskočí modrá obrazovka.
pripájam log súbor
[enigma2_crash_1573144761.log](https://github.com/mtester270/archivczskpremium/files/3820771/enigma2_crash_1573144761.log)

**Comment by mtester270** [comment]
Skuste instalaciu vykonat cez telnet, samozrejme potom restartovat box.
