### ISSUE TITLE
premium

### ISSUE THREAD

**Issue by 19palo19** [mtester270/archivczskpremium#24]
ako to zaplatit?

**Comment by mtester270** [comment]
Skuste zacat instalaciou a citanim.

**Comment by 19palo19** [comment]
A ja že máte záujem aby sa platilo.archivy používam už dlhé roky

Dňa po 25. 11. 2019, 21:51 mtester270 <notifications@github.com> napísal(a):

**Comment by mtester270** [comment]
Bud som nepochopil ja alebo ste nepochopili vy. Ja nic od vas nechcem je to vasa vobla co chcete pouzivat. Vsetko sa dozviete ked nainstalujete verziu 1.0 ktora je zdarma a kebyze si date kusok namahy tak to zistite
