### ISSUE TITLE
archivcsskpremium a dreambox one

### ISSUE THREAD

**Issue by tigana1981** [mtester270/archivczskpremium#26]
Poprosim o radu ,pri nainstalovani na dreambox one ,image dmm experimental mi hodi hlasku;
![untitled](https://user-images.githubusercontent.com/58422794/70396165-a6df4f00-1a06-11ea-98f3-8d20ec211912.png)

**Comment by Ciksa** [comment]
Nainstaluj si aj kniznicu do pythonu a to konkretne pycrypto.

**Comment by tigana1981** [comment]
Ak myslíš python-pycrypto_2.5-r0.4_armhf.1.deb. Tak to som inštaloval spolu s archivczskpremium

**Comment by Ciksa** [comment]
Nie, nakolko ta tebou spominana kniznica je pre 920ku s OE2.5 a ty mas One s OE2.6.

**Comment by tigana1981** [comment]
Aj som si myslel že to nepôjde ale skúsil som. Môžez mi poradiť odkiaľ stiahnem knižnicu pre OE 2.6?

**Comment by Ciksa** [comment]
Kedze pises ze mas v boxe image Experimental ta z ich feedu - https://dreamboxupdate.com/opendreambox/2.6/unstable/r0/dreamone/deb/index.html

**Comment by tigana1981** [comment]
Ďakujem za radu, našiel som to a stiahol, vyskúšam keď prídem domov s práce a dám vedieť či to funguje.

**Comment by tigana1981** [comment]
Takze po nainstalovani kniznice, archivczskpremium je prazdny
![untitled](https://user-images.githubusercontent.com/58422794/70479823-79fe6b00-1ade-11ea-8c58-0a7f938841af.png)

**Comment by Ciksa** [comment]
Kedze sa mi nechce tapat co a ako si instaloval a co vsetko tam chyba ci je spatne tak ak ti mozem poradit, cele to vydrb a znovu nainstaluj. Image posledne experimental https://dreamboxupdate.com/opendreambox/2.6/unstable/images/dreamone/dreambox-image-dreamone-20191122.tar.xz k tomu tu kniznicu pycrypto https://dreamboxupdate.com/opendreambox/2.6/unstable/r0/dreamone/deb/aarch64/python-pycrypto_2.5-r0.4_arm64.deb a po restarte samotny Archiv https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/archivczskpremium_1.0-20191204.deb a na 150% ti to pojde.
![1](https://user-images.githubusercontent.com/44697180/70507524-d4261d00-1b2c-11ea-82a4-7a4f2390e13d.png)
![2](https://user-images.githubusercontent.com/44697180/70507526-d7210d80-1b2c-11ea-9d28-91b0beef9db4.png)

**Comment by tigana1981** [comment]
Nie je problém, spravím čistú inštalaciu a skúsim to, včera ma to napadlo ale o pol noci po práci sa mi to už nechcelo. Ďakujem ti za tvoj čas a radu.

**Comment by Ciksa** [comment]
V pohode, pokial spravis ako som ti pisal a pouzijes subory z odkazov co som sem dal tak na 150% ti to pojde.

**Comment by tigana1981** [comment]
Ok, ešte raz ďakujem, dám vedieť výsledok.

**Comment by mtester270** [comment]
Dik ze si mu to vyjasnil Warder. A kedze nemam DM a problem je len medzi gaucom a TV tak zatvaram.
