### ISSUE TITLE
Doplnok TA3

### ISSUE THREAD

**Issue by Ciksa** [mtester270/archivczskpremium#27]
Mozes sa pozriet na doplnok TA3 ? Ked sa spusti tak sa zobrazi ponuka
![1](https://user-images.githubusercontent.com/44697180/70554679-e2505980-1b7d-11ea-8675-9b5b97909466.png)
- prva polozka Live je nefunkcna (dole v lavom rohu len preblikne Nacitavam ...)
- druha polozka Spravodajstvo aj tretia Publicistika je funkcna.
Ak budes mat cas a chut pozri sa nato. Prikladam log z archivu aj zo samotneho ta3 adonu
[ta3.zip](https://github.com/mtester270/archivczskpremium/files/3946434/ta3.zip) Mozno k niecomu pomozu.

**Comment by mtester270** [comment]
opravene, v pripade zaujmu o danu opravu pred dalsou aktualizaciu je potrebne napisat email na archivczsk@gmail.com (nutne uhradit poplatok).
