### ISSUE TITLE
Orange tv

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#28]
Ahoj,
je tento doplnok funkčný? Odkaz v ňom na bližšie info nefunguje. 
V súvislosti s info s extrémnym zdražovaním freesatu Light rozmýšľam nad základnou ponukou od nich. 
Ďakujem za info a prajem PF2020

**Comment by mtester270** [comment]
V archive to je momentalne nefunkcne mozno bude tak za 2 3 mesiace. Alebo je jedno pohodlnejsie riesenie tu http://chaossevn.aspifyhost.cz/osport.
