### ISSUE TITLE
Font - zoznam doplnkov

### ISSUE THREAD

**Issue by dzupo** [mtester270/archivczskpremium#29]
Zdravim, po poslednej aktualizácii vidím zoznam po spustení takto:
![IMG_20200119_174648](https://user-images.githubusercontent.com/51127437/72684804-0d668b00-3ae4-11ea-8794-858a2facbf38.jpg)
Vu+ UNO 4k SE a VTI 14.0.5
V čom je problém?
Ďakujem.

**Comment by Ciksa** [comment]
Ja by som sa prvorade pozrel aky skin mate pouzity pre ArchivCZSK. Nemyslim celkovy skin v boxe ale v aplikacie ArchivCZSK.
Stlacte Modre (Nastavenia) a hned v prom riadku uvidte a da sa menit podla rozlisenia. Ak mate Dreambox pouzite ten kde je v nazvu pouzita skratka *dmm* .

**Comment by dzupo** [comment]
Default_fhd_font. Skúšam to meniť, ale po uložení sa nič nemení.

**Comment by Ciksa** [comment]
Nastav si to na AUTO, stlac Zelene tlacidlo (Ulozit), ukonci plugin a restartni aj cely box. Potom skus ci ti to pomohlo.

**Comment by dzupo** [comment]
Ok, teraz je to v poriadku. Ďakujem.
