### ISSUE TITLE
Open ATV 6.3 - Problem: nenajdeny subor AES.so

### ISSUE THREAD

**Issue by jdemovic** [mtester270/archivczskpremium#3]
Pri spustani pluginu je problem, ze nevie najst subor AES.so.
<img src="https://www.dropbox.com/s/wsq6s44b5pevo59/archivczsk-premium-error.png?raw=1">

Pritom subor v umiestneni existuje (kontroloval som aj male/velke koli ceste):
<img src="https://www.dropbox.com/s/s6rnhzle2p42qh5/archivczsk-premium-error-path.png?raw=1">

P.S: nainstaloval som aj fix.
Pekny den
J

**Comment by mtester270** [comment]
Presny nazov fixu mi napis, lebo asi si instaloval stary podla vypisu co si dal. Taktiez si neuviedol box pouzivas.

**Comment by jdemovic** [comment]
Ahoj,
Fix mam archivczskpremium-fix-1_1_0.ipk
Zariadenie Dinobot 4k+
J

**Comment by mtester270** [comment]
Co ti pisalo ked si instaloval to ipk?

Skus mi este raz odfotit zlozku Cipher z boxu nech vidim vsetky subory

**Comment by jdemovic** [comment]
Ahoj,
prikladam screenshot z instalacie master IPK:
<img src="https://www.dropbox.com/s/fg783jii4nqbj2n/instalacia.png?raw=1">
Instalacia FIX: fix uz existuje
<img src="https://www.dropbox.com/s/l42bs9skp8va9eo/instalacia_fix.png?raw=1">

A obsah adresara Cipher
<img src="https://www.dropbox.com/s/27oqnlrcanbbx6t/obsah_cipher.png?raw=1">

Skor sa nedalo ;) Bol som mimo moznosti sa vrtat v boxe ,,,
J

**Comment by mtester270** [comment]
Podla toho co si pastol sa neprepisal aes.so preto ti to nejde. Takze 
opkg remove (nazov package si zistis cez opkg list)
Alebo si stiahni .ipk do PC otvor v 7zip rozbalis a dany subor si prepis v boxe das restart a pojde.
