### ISSUE TITLE
Neúspešná aktualizácia 

### ISSUE THREAD

**Issue by damakama** [mtester270/archivczskpremium#30]
Mám problém s aktualizáciou. Terajšia verzia je 1.1.3., no aktualizácia na 2.0 nebola úspešná aj napriek tomu, že som vypol a zapol automatické aktualizácie.

**Comment by Ciksa** [comment]
A co tak aj napisat AKY mas Box, co za image mas v nom, PRIPOJIT nejaky LOG..... ?

**Comment by damakama** [comment]
Sorry,


2020/02/10 11:17:09 00000000 s     (main) Host name      = vusolo2
2020/02/10 11:17:09 00000000 s     (main) Release        = 3.13.5
2020/02/10 11:17:09 00000000 s     (main) Version        = #1 SMP Wed Nov 14 01:34:08 CET 2018
2020/02/10 11:17:09 00000000 s     (main) Machine        = mips
2020/02/10 11:17:09 00000000 s     (main) Stb model      = dm8000
2020/02/10 11:17:09 00000000 s     (main) Stb vumodel    = vusolo2
2020/02/10 11:17:09 00000000 s     (main) Stb boxtype    = vusolo2

image VTi

**Comment by Ciksa** [comment]
Ten vypis z logu startovania Oscamu si mozes ........ ( dm8000 a hned aj vusolo2) :-))))))

Takze len v kratkosti:
- Zazalohuj si adresar archivCZSKpremium z /usr/lib/enigma2/python/Plugins/Extensions/ a vymaz ho. -- Restartni komplet box.
- Stiahni si https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/archivczskpremium_1.0-12122019.ipk
- Nainstaluj ho a restartni komplet box
- Stlac Menu, vyber a potvrd Moduly, vyber a spusti ArchivCZSKPremium
- Plugin sa opyta ci sa ma Aktualizovat .....

**Comment by mtester270** [comment]
Verzia 1.1.3 pre premium verziu neexistuje. V aktualizacii z 4.12. sa menil sposob aktualizacie ale s tym je spojene len to ze na najnovsiu aktualizaciu v2 sa dostanete po dvoch platbach ak uz mate naistalovanu starsiu verziu 1.0 (to neplati pokial naistalujete prevydanu verziu 1.0).

Viac info je v release:
https://github.com/mtester270/archivczskpremium/releases

https://github.com/mtester270/archivczskpremium/releases/tag/verzia_1
