### ISSUE TITLE
Nefunkčnost na VU+ Duo4k

### ISSUE THREAD

**Issue by msoucek-volny-cz** [mtester270/archivczskpremium#31]
Zkusil jsem nainstalovat na VU+ Duo 4k pomocí Telnetu a právě jsem ArchivCZSK aktualizoval. Před aktualizací i po ní nejde spustit, resp. na obrazovce není nic vidět a malém displeji se zobrazí název doplňku. Settopbox na nic nereaguje, jen po stisku tlačítka "menu" na DO systém spadne do zelené obrazovky. Připojuji Crashlogy systému i Archivu. Nešlo by s tím něco udělat prosím?

[enigma2_crash_1583427618.log](https://github.com/mtester270/archivczskpremium/files/4294222/enigma2_crash_1583427618.log)

[archivCZSKpremium.log](https://github.com/mtester270/archivczskpremium/files/4294250/archivCZSKpremium.log)

**Comment by mtester270** [comment]
Podla vsetkeho mate problem vo zvolenom vzhlade enigmy. Takze by som skusil zmenit SKIN (vzhlad) na nejaky default co ma vas image. Po zmene a restarte pristroja skuste spustit archiv. Pripadne vymazat definovany vzhlad pre archiv (ak ho mate nadefinovany) v subore /etc/enigma2/settings kde najdite riadok config.plugins.archivCZSKpremium.skin (subor je mozne menit len pri vypnutom GUI, ak neviete o com pisem tak navod si najdite na internete).

Ak nic nepomoze tak odzalohovat archiv (navod najdete na ab-fore) a preinstalovat cely pristroj a nasledne obnovit archiv.

**Comment by msoucek-volny-cz** [comment]
Zdravím,
archiv mám instalovaný na čerstvě instalovaný poslední "factory" image a pro enigmu používám default skin. ArchiveCZSK je první a zatím jediný plugin, který jsem nainstaloval. Zkusil jsem přepnout i na ostatní (dva) skiny, které jsou součástí image, výsledek je však stejný. V /etc/enigma2/settings nadefinovaný žádný styl nemám. Podle logu asi enigma2 nezná globální proměnnou dom_skins, možná nějaká odchylka enigmy u přístrojů VU+. Jsou nějaké informace, zda někdo úspěšně používá ArchivCZSK na VU+ ?

**Comment by Ciksa** [comment]
Kvoli tebe msoucek-volny-cz som sa "vlupal" na dialku jednemu z klientov co maju VU+ Zero4K. Nainstalovane posledne VTi 14.0.6 a tak som mu tam nahral archivczskpremium_1.0-12122019.ipk   restartol box a ziaden problem.
![vti-1](https://user-images.githubusercontent.com/44697180/76160574-9cc70c80-612b-11ea-8229-2b74a9365110.jpg)
![vti-2](https://user-images.githubusercontent.com/44697180/76160581-abadbf00-612b-11ea-80fa-90db97449459.jpg)
Aktualizaciu som potvrdil - **Mark prepac mi ale potom si zrus cakanie na platbu J248R4WS**
![vti-3](https://user-images.githubusercontent.com/44697180/76161959-9f7c2e80-6138-11ea-89e5-1c8f3fe1789a.jpg)
![vti-4](https://user-images.githubusercontent.com/44697180/76161961-a3a84c00-6138-11ea-94ab-e4eb2b3994bb.jpg)
![vti-5](https://user-images.githubusercontent.com/44697180/76161963-a73bd300-6138-11ea-9f30-990f555da5fa.jpg)

**Comment by msoucek-volny-cz** [comment]
Děkuji za otestování, zkusím to tedy ještě s tím VTi. Jak jsem psal, mám v přístroji tovární FW stažený z repozitáře VU+ a nic jiného jsem tam neinstaloval. Vyzkouším a dám vědět.

**Comment by Ciksa** [comment]
Urcite by som pouzil iny nez tovarny "factory" image.  Sorry ale nemam tu momentalne ziadny volny VU+ 4K box aby som sa mohol hrat a poradit nieco ine.

**Comment by mtester270** [comment]
Este som nevidel kto by pouzival tovarensky image, takze sa niet comu cudovat ze to nejde.

V standardnych image ako Vti, openAtv, blackHole, openLli vsetko funguje ako ma.

Takze zatvaram.

Ps: warder stym si nerob starosti 😉
