### ISSUE TITLE
Neuspesna instalace

### ISSUE THREAD

**Issue by Mikou1** [mtester270/archivczskpremium#33]
Zdravim, po ciste instalaci Openatv 6.3 na Zgemma H7S jsem nainstaloval doporucenym zpusobem pres putty ArchivCZSK Premium. Po spusteni se objevila znama hlaska... counter.so: cannot open shared object file... Pokusil jsem se o opravu dle napovedy oprava se stahla, ale instalace opravy neprobehla viz konec logu v priloze... Co s tim muzu delat?

[log putty.txt](https://github.com/mtester270/archivczskpremium/files/4363402/log.putty.txt)

**Comment by mtester270** [comment]
Pise vam to ze fix balicek uz mate naistalovany takze netusim co stym robite (standardne archiv v openatv6.3 fjnguje). Ked tak ho treba odinstalovat a tak instalovat ale asi vam to nepojde tak ci tak. S tym sa doporucim obratit na  nejake forum a najst niekoho kto ma rovnaky box.
