### ISSUE TITLE
Nejde nic přehrát

### ISSUE THREAD

**Issue by drahlin** [mtester270/archivczskpremium#34]
Od neděle nejde spustit žádné přehrávání filmu či seriálu v sat.přijímači na Stream Cinema i když ostatní fungují např.Sosáč. Žádné úpravy ani aktualizace jsem nedělal. Stream přes internet funguje normálně.Používám archiv czsk premium 1.0.5.

**Comment by Ciksa** [comment]
Restartni si box a potom si zaktualizuj plugin na najnovsiu verziu - z dnesneho dna.

**Comment by drahlin** [comment]
Takže,kdo má neplacenou verzi Archivu cz/sk si musí koupit akualizaci?

**Comment by mtester270** [comment]
nemusi nic kazdeho volba
