### ISSUE TITLE
Ndejde nic přehrát

### ISSUE THREAD

**Issue by drahlin** [mtester270/archivczskpremium#35]
Nevím proč jsi předchozí problém zamknul. Ještě se chci zeptat za ty,kteří nepužívají placenou verzi CZ/SK archivu co mají dělat,aby mohli sledovat Stream cienemu.Děkuji

**Comment by Ciksa** [comment]
Ti co nemaju platenu Premium verziu a chcu pozerat SC tak si musia zaplatit a nainstalovat Premium verziu a zaktualizovat ju na poslednu verziu.

**Comment by drahlin** [comment]
No nevím zda tvoje rady jsou vždy objektivní ale napadlo mě co si nainstalovat Kodi ? Tam by to hádám mělo jít neplacené.Jsi opravdu vtipný!

**Comment by Ciksa** [comment]
No ja mu len dobre poradim a este sa mu to nepaci a pritom moje rady su VZDY len dobre a objektivne ! :-))))

**Comment by mtester270** [comment]
off topic, otazky na ne-premium verziu smeruj inde ja s tym nic nemam. Chapeme?
