### ISSUE TITLE
DM820 HD image dream OS OE 2.5

### ISSUE THREAD

**Issue by Janyck1982** [mtester270/archivczskpremium#36]
Mám nainštalovaný archiv cz/sk premium 1.0.0 tamten starý som dal vymazať a tu je log že mi nefunguje v tejto verzii stále zelená smrť,keď kliknem na hocijaký doplnok v tejto verzii
[archivCZSKpremium.log](https://github.com/mtester270/archivczskpremium/files/4505528/archivCZSKpremium.log)

**Comment by mtester270** [comment]
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed 

Chyba SSL, na DM pomaha naistalovat CSFD plugin. Preco zavo naco netusim DM nevlastnim.

**Comment by Janyck1982** [comment]
Ako sa posielajú peniaze cez paypal na archiv cz/sk premium myslím postup 
zapnem stream cinema a potom Trakt.tv a vypise mi toto na obrazovke:Prosím vykonajte autorizaciu zariadnia na URL https://trakt.tv/activate s týmto kodom: osemmiestny kod az nasledne stlacte ok,

    Am Montag, 20. April 2020, 21:52:23 MESZ hat mtester270 <notifications@github.com> Folgendes geschrieben:  
 
 


Closed #36.

**Comment by mtester270** [comment]
O moj boze
https://m.youtube.com/watch?v=t-v7oNi7c-o

**Comment by Janyck1982** [comment]
peniaze som poslal neviete mi ten archivczsk premium opraviť, aby mi nehadzalo zelenu smrtpouživam Teamviewer

Chaoss Evolution-záporné 1,2021. apríla 2020Payment Sent   
   - Spôsob úhrady:
      - Debetná karta MasterCard x-2106
      - Na výpise z karty uvidíte text „PAYPAL *CHAOSS EVN“.
   
   - Category
      - Online služby
   
   - ID transakcie
      - 1D2841905M8951645
   
   - Informácie o predajcovi
      - Chaoss Evolution
      - mtester270@gmail.com
   
   - Podrobnosti nákupu
      - Aktualizácia SW1,20 EUR
   
      - 
      - Súčet1,20 EUR


    Am Montag, 20. April 2020, 22:08:58 MESZ hat mtester270 <notifications@github.com> Folgendes geschrieben:  
 
 


O moj boze
https://m.youtube.com/watch?v=t-v7oNi7c-o

**Comment by Janyck1982** [comment]
13:16:06.693 [INFO] Checking archivCZSK premium update...13:16:06.694 [INFO] ############# modified updater V3 #############13:16:06.842 [ERROR] ArchivUpdater update failed.Traceback (most recent call last):  File "engine/updater.py", line 85, in checkUpdate  File "engine/tools/util.py", line 152, in download_web_file  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen    return opener.open(url, data, timeout)  File "/usr/lib/python2.7/urllib2.py", line 437, in open    response = meth(req, response)  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response    'http', request, response, code, msg, hdrs)  File "/usr/lib/python2.7/urllib2.py", line 469, in error    result = self._call_chain(*args)  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain    result = func(*args)  File "/usr/lib/python2.7/urllib2.py", line 656, in http_error_302    return self.parent.open(new, timeout=req.timeout)  File "/usr/lib/python2.7/urllib2.py", line 431, in open    response = self._open(req, data)  File "/usr/lib/python2.7/urllib2.py", line 449, in _open    '_open', req)  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain    result = func(*args)  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open    context=self._context)  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open    raise URLError(err)URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
13:16:06.854 [DEBUG] ContentProvider start13:16:08.633 [DEBUG] Opening item '<PCategory - VĹˇetky doplnky>'...13:16:14.884 [DEBUG] ContentProvider pause13:16:29.382 [DEBUG] HTTP supported13:16:29.387 [DEBUG] HLS supported13:16:29.392 [DEBUG] MMS supported13:16:29.398 [DEBUG] RTMP not supported (some file missing '/usr/lib/gstreamer-*')...'libgstrtmp.so' is missing...'/usr/lib/librtmp.so.0' or '/usr/lib/librtmp.so.1' is missing...13:16:29.404 [DEBUG] RTSP supported for 100%...13:16:29.409 [DEBUG] MP4 supported13:16:29.414 [DEBUG] ASF supported13:16:29.419 [DEBUG] AVI supported13:16:29.424 [DEBUG] FLV supported13:16:29.429 [DEBUG] MKV supported13:16:29.434 [DEBUG] MP4 supported13:16:33.514 [DEBUG] HTTP supported13:16:33.519 [DEBUG] HLS supported13:16:33.524 [DEBUG] MMS supported13:16:33.530 [DEBUG] RTMP not supported (some file missing '/usr/lib/gstreamer-*')...'libgstrtmp.so' is missing...'/usr/lib/librtmp.so.0' or '/usr/lib/librtmp.so.1' is missing...13:16:33.536 [DEBUG] RTSP supported for 100%...13:16:33.541 [DEBUG] MP4 supported13:16:33.546 [DEBUG] ASF supported13:16:33.551 [DEBUG] AVI supported13:16:33.556 [DEBUG] FLV supported13:16:33.562 [DEBUG] MKV supported13:16:33.567 [DEBUG] MP4 supported13:16:37.041 [DEBUG] HTTP supported13:16:37.046 [DEBUG] HLS supported13:16:37.052 [DEBUG] MMS supported13:16:37.058 [DEBUG] RTMP not supported (some file missing '/usr/lib/gstreamer-*')...'libgstrtmp.so' is missing...'/usr/lib/librtmp.so.0' or '/usr/lib/librtmp.so.1' is missing...13:16:37.065 [DEBUG] RTSP supported for 100%...13:16:37.072 [DEBUG] MP4 supported13:16:37.077 [DEBUG] ASF supported13:16:37.083 [DEBUG] AVI supported13:16:37.089 [DEBUG] FLV supported13:16:37.094 [DEBUG] MKV supported13:16:37.099 [DEBUG] MP4 supported13:19:04.850 [DEBUG] ContentProvider resume13:19:15.971 [DEBUG] ContentProvider stop13:19:17.918 [DEBUG] ContentProvider start13:19:22.826 [DEBUG] Opening item '<PCategory - VĹˇetky doplnky>'...13:19:23.747 [DEBUG] ContentProvider pause13:19:24.755 [DEBUG] ContentProvider resume13:19:26.616 [DEBUG] ContentProvider stop13:19:32.506 [DEBUG] ContentProvider start13:19:34.297 [DEBUG] Opening item '<PCategory - VĹˇetky doplnky>'...13:19:37.023 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...13:19:37.028 [DEBUG] ContentProvider start13:19:37.030 [DEBUG] VideoAddon(Stream Cinema-1.0.0) adding importer13:19:37.033 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer13:20:01.185 [DEBUG] adding addon=VideoAddon(DigiGO-1.0.0) (plugin.video.digigo)13:20:01.210 [DEBUG] adding addon=VideoAddon(TA3-1.0.0) (plugin.video.ta3.com)13:20:01.235 [DEBUG] adding addon=VideoAddon(joj.sk-1.0.0) (plugin.video.joj.sk)13:20:01.264 [DEBUG] adding addon=VideoAddon(iVysilani - Ceska televize-1.0.0) (plugin.video.ivysilani)13:20:01.321 [DEBUG] adding addon=VideoAddon(Stream Cinema-1.0.0) (plugin.video.stream-cinema)13:20:01.350 [DEBUG] adding addon=VideoAddon(markiza.sk-1.0.0) (plugin.video.markiza.sk)13:20:01.363 [DEBUG] adding addon=ToolsAddon(stream resolver-1.0.0) (script.module.stream.resolver)13:20:01.383 [DEBUG] adding addon=VideoAddon(Stream TV Archiv-1.0.0) (plugin.video.streamtv)13:20:01.415 [DEBUG] adding addon=VideoAddon(O2TV-1.0.0) (plugin.video.o2tv)13:20:01.435 [DEBUG] adding addon=VideoAddon(Nova Plus TV Archiv-1.0.0) (plugin.video.novaplus)13:20:01.445 [DEBUG] adding addon=ToolsAddon(Common python modules-1.0.0) (script.module.common)13:20:01.471 [DEBUG] adding addon=VideoAddon(rtvs.sk-1.0.0) (plugin.video.rtvs.sk)13:20:01.534 [DEBUG] adding addon=VideoAddon(Soubory Online-1.0.0) (plugin.video.online-files)13:20:01.569 [DEBUG] adding addon=VideoAddon(iPrima-1.0.0) (plugin.video.primaplay)13:20:01.607 [DEBUG] adding addon=VideoAddon(Sosac-1.0.0) (plugin.video.sosac.ph)13:20:01.631 [DEBUG] adding addon=VideoAddon(OrangeTV-1.0.0) (plugin.video.orangetv)13:20:01.657 [DEBUG] adding addon=VideoAddon(Mestska TV Ruzomberok-1.0.0) (plugin.video.mtr.sk)13:20:01.681 [DEBUG] adding addon=VideoAddon(Drtinova Veselovsky TV-1.0.0) (plugin.video.dvtv.cz)13:20:01.682 [DEBUG] Doplnky (CZ & SK) successfully loaded13:20:01.683 [DEBUG] initializing addons...13:20:01.755 [DEBUG] Screen width 1920 px13:20:01.757 [DEBUG] loading skin /usr/lib/enigma2/python/Plugins/Extensions/archivCZSKpremium/gui/skins/default_dmm_fhd.xml

**Comment by mtester270** [comment]
CSFD plugin ste si naistaloval? 
A nie nemohol support nerobim lebo mi to nik nezaplati. Ste ochotny zaplatit ked vam to opravim cez TeamViewer? (ale 1eur to nebude)

**Comment by Janyck1982** [comment]
Nie nenainstaloval,ak sa mi to nepodarí spojazdniť tak za koľko ste ochotný to spraviťDňa 21. 4. 2020 13:41 používateľ mtester270 <notifications@github.com> napísal:
CSFD plugin ste si naistaloval?
A nie nemohol support nerobim lebo mi to nik nezaplati. Ste ochotny zaplatit ked vam to opravim cez TeamViewer? (ale 1eur to nebude)

**Comment by mtester270** [comment]
minimalna cena je 10eur zvysok zalezi od toho kolko to bude trvat.

**Comment by mtester270** [comment]
minimalna cena je 10eur zvysok zalezi od toho kolko to bude trvat.

**Comment by Janyck1982** [comment]
uz by to malo isť,kedy ma aplikacia vyzve k aktualizácii cez email alebo cez spravu na paypal alebo cakat v prijimaci ked mi naskoci sprava k aktualizacii
   ----- Weitergeleitete Nachricht ----- Von: "janbunda@yahoo.de" <janbunda@yahoo.de>An: mtester270/archivczskpremium <reply@reply.github.com>Gesendet: Dienstag, 21. April 2020, 13:48:22 MESZBetreff: Re: [mtester270/archivczskpremium] DM820 HD image dream OS OE 2.5 (#36)
 Nie nenainstaloval,ak sa mi to nepodarí spojazdniť tak za koľko ste ochotný to spraviť

Dňa 21. 4. 2020 13:41 používateľ mtester270 <notifications@github.com> napísal:




CSFD plugin ste si naistaloval?
A nie nemohol support nerobim lebo mi to nik nezaplati. Ste ochotny zaplatit ked vam to opravim cez TeamViewer? (ale 1eur to nebude)

**Comment by mtester270** [comment]
restartujte box a pri spusteni archivu premium vam musi vyskocit hlaska.

ak nie tak vam stale nieco nejde
