### ISSUE TITLE
sledovane

### ISSUE THREAD

**Issue by drozkar** [mtester270/archivczskpremium#37]
Ahoj, doplněk sc je super, ale mám problém u seriálů.
Pokud již mám nějaký seriál shlédnutý, a chci se na něj po nějaké době podívat, nejde ho už nastavit jako neviděný, ani smazat z watchlistu… Nejde to ani ze složky sledované, ani z výběru seriálů
Jedině každý díl zvlášť. 
Stahuju si každou aktualizace a v těch prvních, po tom co jsi to implementoval i na mé přání to fungovalo perfektně... 
Několik posledních aktualizací už to tak není, jde to prosím nějak opravit?
VU+ Ultimo 4K, image VTI 14.0.6

**Comment by mtester270** [comment]
Nechapem scenaru, prosim uvies konkretny a rozpisany priklad krok po kroku.

Poprosim mailom nie tu.

**Comment by drozkar** [comment]
Spustím archív, spustím sc.Vyberu seriály. Potom sledované.V této záložce jsou seriály které jsem už viděl. Ale chtěl bych je vidět znova. Vyberu konkrétní seriál, přes menu dám že chci vymazat z watchlistu a operace se nezdaří. Totéž se stane když dát že nastavit jako neshlédnuté.Funguje to jen když vezmu přímo díl seriálu. Ale to odznačí pouze ten jeden díl. Stejně se to chová i když vyberu záložku se seriálem přímo v seriálech. Zkusil jsem vypnout traktv a znova zapnout. Nepomohlo to. Nový seriál se samozřejmě do záložky sledované přidá
-------- Původní zpráva --------Od: mtester270 <notifications@github.com> Datum: 21.04.20  21:38  (GMT+01:00) Komu: mtester270/archivczskpremium <archivczskpremium@noreply.github.com> Cc: drozkar <vir@inmail.sk>, Author <author@noreply.github.com> Předmět: Re: [mtester270/archivczskpremium] sledovane (#37) 
Nechapem scenaru, prosim uvies konkretny a rozpisany priklad krok po kroku.
Poprosim mailom nie tu.

**Comment by mtester270** [comment]
Prosim ta citat vies? Tak preco mi to pises na github!
