### ISSUE TITLE
nový subsupport

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#38]
Testujem nové úložisko, predpokladám, že relácie z nového úložiska sú označené hviezdičkou? 
Bude nový subsupport možné len jednoducho aktualizovať zo súčasného 1.5.5.? Bude fungovať na oboch úložiskách? 
Ak na to bude čas, uvítal by som nejaký návod.
skvelá práca. ďakujem

**Comment by mtester270** [comment]
predpoklad spravny
SS si stiahni predsa odtialto https://github.com/mtester270/archivczskpremium/releases/tag/verzia_5 a to uz snad preinstalovat zvladnes
