### ISSUE TITLE
titulky nelze spustit

### ISSUE THREAD

**Issue by miro350** [mtester270/archivczskpremium#39]
titulky nelze spustit, film bezi bez problemu, pri spusteni vnorenych titulku nasleduje reboot systemu, vnorene titulky povoleny
dreamos 2.6  archiv premium v5 20.04.2020, titulky subssupport_1.5.7-20200421_all.deb
log archiv
20:03:30.243 [INFO] Checking archivCZSK premium update...
20:03:30.838 [INFO] No new update found.
20:04:10.796 [ERROR] Set embeded subtitles failed.
Traceback (most recent call last):
  File "BuildPackage/Compile_Archiv/engine/player/player.py", line 407, in setEmbededSubtitle
AttributeError: 'iPlayableServicePtr' object has no attribute 'subtitle'

20:07:14.201 [ERROR] Set embeded subtitles failed.
Traceback (most recent call last):
  File "BuildPackage/Compile_Archiv/engine/player/player.py", line 407, in setEmbededSubtitle
AttributeError: 'iPlayableServicePtr' object has no attribute 'subtitle'

**Comment by mtester270** [comment]
reinstall na tuto verziu
[SS_OE2.5 deb](https://github.com/mtester270/archivczskpremium/releases/download/v1.0.0/subssupport_OE2.5_1.5.6-r0.2_all.deb)

nasledne by som skopiroval obsah /subssupport/plugin/* z tohto [commitu](https://github.com/mx3L/subssupport/tree/2a4eee41b53cd89963673f0d22cda5cd1594cde7) do pristroja na cestu 
/usr/lib/enigma2/python/Plugins/Extensions/SubsSupport/

ak nepojde tak sa treba obratit na [github autora](https://github.com/mx3L/subssupport)
