### ISSUE TITLE
prechod na premium 2

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#4]
Ahoj,

znovu sa objavila možnosť prejsť na premium. všetko sa nainštalovalo a pri spustení archívou zamrznutie. Pomohol len tvrdý reštart. Čo teraz?

log:
May  7 19:32:47 vuuno4kse user.err kernel: [   37.966532] [SC]: !!!unknown cmd 0x540b
May  7 19:32:51 vuuno4kse user.err kernel: [   41.079594] [SC]: !!!unknown cmd 0x540b
May  7 19:33:10 vuuno4kse cron.err crond[1112]: time disparity of 25954172 minutes detected
May  7 19:37:11 vuuno4kse auth.info login[2544]: root login on 'pts/0'

**Comment by gladius70** [comment]
VU+ UNO 4K SE, VTI 13.0.9, Amiko A3, Unicable LNB Inverto, OSCAM: 1.20-unstable_svn Build: r11086

**Comment by mtester270** [comment]
To fakt netusim. Vymaz alebo si ich niekde odloz zlozky z pluginov /usr/lib/python.../Plugins...
archivczsk
archivczskpremium

Restartni box a nainstalj si to cez IPK balicek. Taktiez neviem ktory plugin spustas kedze si to napisal ako napisal.

**Comment by gladius70** [comment]
Spúšťal som archívy premium.
Vyskúšam teda vymazať a cez telnet nainštalovať ipk balík. Snáď to stihnem do piatku. Doma som zatiaľ obnovil staré archívy zo zálohy.

**Comment by mtester270** [comment]
Skus este raz ten prechod na premium pretoze cosi sa tam este naslo ale len v pripade ak si mal v povodnom archive vlastnu kategoriu kde si mal nahadzane doplnky ktore pouizvas.

**Comment by gladius70** [comment]
Áno. To bude ono. Mal som vlastný zoznam doplnkov, kde som mal len tie, ktoré som používal. Aktualizacia na premium mi už asi nepôjde, pretože zo zálohy som obnovil archívy v. 1.0 a tie sa nevedno prečo nechcú aktualizovať na vyššiu verziu. Vymažem ich a cez telnet nainštalujem priamo premium verziu. Len som ešte dnes mimo.

**Comment by mtester270** [comment]
Tu mas zip latest len rozbal kam to patri restart a ponukne ti premium
https://github.com/mx3L/archivczsk/blob/master/build/plugin/update/version/archivczsk-1.2.2.zip

Povazujme za vyriesene, zatvaram.
