### ISSUE TITLE
ArchivCZSK Premium

### ISSUE THREAD

**Issue by markus1766** [mtester270/archivczskpremium#40]
Ahoj , po aktualizácii z  20.04.2020 sa mi stáva že pri prehávaní sa prijímač VU+ UNO 4K SE reštartuje  (OpenATV 6.2) , Prikladám log , ďakujem.
[enigma2_crash_1587831163.log](https://github.com/mtester270/archivczskpremium/files/4534876/enigma2_crash_1587831163.log)

**Comment by mtester270** [comment]
Ziadnu chybu archivu nevidim takze vas problem s archivom nesuvisi. Chyba asi je
18:12:43.9302 [   ] bsod.cpp:348 handleFatalSignal -------FATAL SIGNAL

Takze mate nieco zle skusil by som reinstall image (nazbudnut zalohu archivu) ale je mozne ze sa jedna o HW chybu. To uz ja vam nemam ako pomoct.

**Comment by markus1766** [comment]
Ak môžete tak dneska pri pozeraní filmu a stlačení pauzi .
[enigma2_crash_1587898362.log](https://github.com/mtester270/archivczskpremium/files/4535188/enigma2_crash_1587898362.log)

**Comment by mtester270** [comment]
Chyba rovnaka, nemam vam ako pomoct bud reinstall alebo sa obratte na nejake forum ja servis boxov nerobim
