### ISSUE TITLE
Stream cinema

### ISSUE THREAD

**Issue by L0th4r** [mtester270/archivczskpremium#41]
Nejde vyhledavat - none

**Comment by Ciksa** [comment]
Ak nemas Premium verziu archivu a hlavne ucet na kra.sk tak sa necuduj.

**Comment by L0th4r** [comment]
Kdybych nemel premium ucet, tak sem nepisu...;-/, je pravda, ze kra.sk nemam jen webshare, ale to by nemelo mit na vyhledavani vliv...

**Comment by GrgoPitic** [comment]
Ale malo WS už nie je podporované na SC to asi preto. Je toho plné fóra. Podporovaný zatial iba kra.sk

**Comment by velavista** [comment]
Takže si zaplatit další premium? Nerozumím tomu, kde je zas problém a na co mi teď bude premium na Webshare?

**Comment by GrgoPitic** [comment]
No na sťahovanie filmov? Predplatné ti ostáva nikto ti nič nezobral. Kľudne sťahuj z WS.

**Comment by Ciksa** [comment]
L0th4r a kolektiv. Zabudnite na webshare, ked nemate ucet na kra tak nepozerate. Ak to tak nieje, tak ma autor urcite poopravi.

**Comment by velavista** [comment]
Dobře, ale kupoval jsem ho abych ho mohl používat ve vůčku, né na pc a jako platit další premium někde, aby mi to fungovalo měsíc určitě nebudu.

**Comment by GrgoPitic** [comment]
Môžeš ho používať aj vo VU je tam ďalší doplnok Online Súbory kde si môžeš vložiť prihlasovacie údaje do doplnku. Je to iné ako SC.

**Comment by velavista** [comment]
Aha, tak moc děkuju

**Comment by L0th4r** [comment]
Koupil jsem kra a stejne nic :-D

**Comment by Ciksa** [comment]
Zapis prihlasovacie udaje do nastavia SC a restartni box.

**Comment by L0th4r** [comment]
Ano to jsem delal :), ale v nastaveni  je VIP days -2, tak to mozna dyl trva nez se to zaktualizuje

**Comment by GrgoPitic** [comment]
Pozri na kra.sk koľko ti ostava dní. Musíš použiť voycher čo ti prišiel do e-mailu. Inak si iba registrovaný nie zaplatený :-)

**Comment by velavista** [comment]
> 
> 
> Ano to jsem delal :), ale v nastaveni je VIP days -2, tak to mozna dyl trva nez se to zaktualizuje

Dej prosím vědět, jestli je to vůbec k něčemu :-D Díky

**Comment by L0th4r** [comment]
> Pozri na kra.sk koľko ti ostava dní. Musíš použiť voycher čo ti prišiel do e-mailu. Inak si iba registrovaný nie zaplatený :-)

Nejsem kokot :D
Pouzil jsem ho hned jak jsem zaplatil, ukazuje mi to 30d

**Comment by Ciksa** [comment]
Daj tomu nejaku chvilku, znovu restartni GUI v boxe (Enigmu) a skus to.

**Comment by icoosk** [comment]
Pekný deň. Mám ten istý problém ako L0th4r, prijímač VU+ Uno 4K SE,  účet na kra zaplatený na 3 mesiace, voucher sa použil automaticky, zadal som prihlasovacie údaje do premium uctu do kra a stále -2 days, skontroloval som aj log a v config.plugins.archivCZSKpremium.archives.plugin_video_stream-cinema.krpass a config.plugins.archivCZSKpremium.archives.plugin_video_stream-cinema.kruser sú udaje spravne ..... reštartoval som prijimač , reštartoval som gui ......, už som pre istotu vymazal aj prihlasovacie udaje na webshare .......  v kodi v telefone mi to nabehlo okamžite ....... ak by niekoho napadlo riešenie vopred ďakujem.

**Comment by mtester270** [comment]
Toto si chodte vypisovat na forum nie tu. Zatvaram a mazem.
