### ISSUE TITLE
Stream-Cinema

### ISSUE THREAD

**Issue by hitman222** [mtester270/archivczskpremium#42]
Ahoj,
mám UNO 4K a ZERO 4K v každém OpenPLI 7.2 Archív Premium a serial Ti,co vraždí na UNE jede normálně a na ZERU jede jen zvuk,kde může být chyba prosím.
Děkuji

**Comment by Ciksa** [comment]
Chyba moze byt v kodeku v akom je spracovany dany serial a ktory procesor Zera akosi nepodporuje.

**Comment by hitman222** [comment]
Dá se to nějak zjistit které kodeky nepodporuje?

**Comment by Ciksa** [comment]
Tusim stare DivX to boli ale ake vsetky dalsie nemam ponatia. Niekde to myslim bolo +- popisane, skus uja Google.

**Comment by hitman222** [comment]
Diky moc.

**Comment by mtester270** [comment]
Povazujem za vyriesene pani. Uzatvaram.

**Comment by Ivan0390** [comment]
Kód 832FDWPA

**Comment by Ciksa** [comment]
Ivan0390 ten kod mu posli na email .
