### ISSUE TITLE
Instalacia archivCZSKpremium

### ISSUE THREAD

**Issue by Murelitto** [mtester270/archivczskpremium#44]
Ahojte, idem presne podla navodu...
1  - zaloha (kopirovanie povoneho premium)

2 - reinstall noveho
nezobrazi sa doplnok, a hodi chybu oko v navode

3 - Instalacia Fixu
vypise chybu:
"Collected errors:
* opkg_prepare_file_for_install: Refusing to load file '/tmp/archivfix.ipk' as it matches the installed version of archivczskpremiumfix (1.1.0)."

A stale sa neviem sa pohnut. Nechapem co robim zle... Je sice pravda ze nie som ziadny expert
Vysledok je ze nemam teraz ziadny doplnok, ale ked dam odinstalovat doplnky tak tak tam je...

fungujem na MAC OS Catalina - PUTTY na MacOS nie je - pouzivam Terminal, VU+ Ultimo 4K, OpenPli 7.2

Dakujem za pomoc. uz som zufaly

**Comment by mtester270** [comment]
najjednoiduchsie resintall na cisty image a potom podla navodu naistalovat a FIX instalovat len ak je potrebne!!!!

ine riesenie telnet:
opkg remove archivczskpremiumfix
opkg remove --force-depends enigma2-plugin-extensions-archivczskpremium
... dalej uz klasicky postup instalacie

fix instaluje:
opkg files archivczskpremiumfix

kazdy subor co nahradza tak odzalohuje s koncovkou *.origin takze revertnut si to mozes aj sam ze si ten subor premenujes na povodny nazov a existujuci subor pred tym vymazes potom samozrejme restart.
/usr/lib/python2.7/site-packages/Crypto/

**Comment by Murelitto** [comment]
dakujem!!!! slape konecne... aj ked som este raz zaplatil, ale tesim sa!!! rad podporim sikovneho vyvojara.

este jedna otazka - mozno mimo ale skusim.
vyberiem film v 4K, obraz slape uplne bez problemov, ale ked prepnem jazyk do CZ tak to zacne chrcat a sekat - pise ze E-AC3 kodek. v com moze byt problem??? v anglictine ide ako nic

**Comment by mtester270** [comment]
Nemam tucha. Nekompatbilne. Ked tak pis email nie do issue
