### ISSUE TITLE
nefunkčnosť pluginu

### ISSUE THREAD

**Issue by gab01980** [mtester270/archivczskpremium#45]
Dobrý deň, obraciam sa na Vás s prosbou o pomoc.  Na uclan.sk som našiel návod, ako postupovať pri inštalácii Vášho pluginu. Všetko prebehlo hladko, zaplatil som tú symbolickú sumu za aktualizáciu, zaregistroval som sa na kra.sk (zatiaľ na mesiac), ale stále mi píše že mám nesprávne meno a heslo. Dočítal som sa, že v boxe tá virtuálna klávesnica dopĺňa divné znaky, ale v /etc/enigma2/settings sa mi to zdá správne, žiadny iný znak tam nevidím. Mám nainštalovanú aj aktualizáciu (v6 z 05.05.2020), ktorá to mala odstrániť. Môžete mi prosím poradiť?

Skúšam to na boxe Amiko Viper 4K51. Ak budete potrebovať, dopošlem nejaké logy alebo iný screenshot.

Vopred ďakujem za ochotu. 

![archivzcsk-01](https://user-images.githubusercontent.com/65647604/82420810-879e2080-9a80-11ea-91a8-a2138cf3d26d.jpg)
![archivzcsk-02](https://user-images.githubusercontent.com/65647604/82420815-8967e400-9a80-11ea-8891-3c348be45875.jpg)
![archivzcsk-03](https://user-images.githubusercontent.com/65647604/82420821-8a991100-9a80-11ea-92a5-170f4004cce9.jpg)
![archivzcsk-04](https://user-images.githubusercontent.com/65647604/82420823-8b31a780-9a80-11ea-8efb-0350ea39871b.jpg)

**Comment by mtester270** [comment]
poslite email na archivczsk@gmail.com
do emailu ako prilohu:
- vsetky logovacie subory /tmp/archiv_logs/*
- a subor /etc/enigma2/settings

o prihlasovacie udaje sa bat nemusite takze prosim mi ich tam nechajte tak ako ich mate zadane teda aspon tie na streamcinema ostatne si kludne zmazte je mi jedno.
