### ISSUE TITLE
Filmy - najnovsie

### ISSUE THREAD

**Issue by Messo8080** [mtester270/archivczskpremium#46]
Zdravim,

Chcem reportovat bug, len neviem ci sa tyka vsetkych, alebo len mna. prejvilo sa mi to minuly tyzden, dovtedy to fungovalo korektne.
Problemova polozka je: **Stream Cinema -> Filmy -> Najnovsie**
Neobsajuhe najnovsie filmy, ale len to co je **Novinky dabovane**. 
Teda obe polozky obsahuju to iste. Mrknite na to, som v tomto doplnku novacik, neviem ci staci zmazat nejaku cache

![image](https://user-images.githubusercontent.com/62379561/82876943-d3960d00-9f39-11ea-93f4-7bb1f0d4b774.png)

**Comment by Ciksa** [comment]
Myslis ze su rovnake ?

Najnovsie
![1](https://user-images.githubusercontent.com/44697180/82879297-0beb1a80-9f3d-11ea-8510-cde7adb28ffd.jpg)

Dabovane
![2](https://user-images.githubusercontent.com/44697180/82879329-173e4600-9f3d-11ea-98f8-ccd00452fc27.jpg)

**Comment by Messo8080** [comment]
Kamen urazu, je ze v mojom obrazku chybaju vsetky EN only polozky.
Je mozne nejaku Cache vyprazdnit? Ako sa to mohlo stat, ze nevidim vsetky polozky?

**Comment by Ciksa** [comment]
Neviem, pytal si sa na zoznamy filmov.
Mozes skusit si zapnut v nastaveni Archivu  cistenie pamate ale ci to bude mat vplyv na "funkciiu zootechnika" neviem. :-)
![3](https://user-images.githubusercontent.com/44697180/82880674-08f12980-9f3f-11ea-80e8-559c0590b76d.jpg)

**Comment by Messo8080** [comment]
To som prave skusal, nic ine som nenasiel. No i po restartoch doplnku, alebo celeho boxu, nacita si len ten moj zoznam, teraz razatne skrateny.... A potom mam Novinky a Novinky dabovane rovnake. To iste mi robi aj na ArchivCZSK nepremium, to som skusal pred polhodkou. 

Zatial dakujem, problem bude asi len u mna

**Comment by Ciksa** [comment]
A nemas len nastaveny nejaky jazykovy filter ?
![4](https://user-images.githubusercontent.com/44697180/82881629-39859300-9f40-11ea-9f69-b7170a856aa5.jpg)

**Comment by Messo8080** [comment]
Bingo.... Mal som tam CZ-SK, a to bolo onooooo.... Ale nemenil som to od cias uvodnej inicializacie, takze to asi neslo a uz to ide :-)

Diky moc, dost si mi pomohol

![image](https://user-images.githubusercontent.com/62379561/82882329-363ed700-9f41-11ea-9233-be73ed6a5b2e.png)
