### ISSUE TITLE
mrznutie pri sťahovaní titulkov cez captcha

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#47]
Zdravím, 

subssuport 1.5.7 funguje ok, pokiaľ pri titulky.com nie je vyžadovaná captcha.
Vtedy mi stroj VU plus uno 4k se, vti 13.0.9 zamrzne a pomôže len tvrdý reštart.
Je to asi možný bug. 
Pomôže inštalovať 1.5.8, kde m3xl v poznámke niečo v tom zmysle naznačuje?

**Comment by mtester270** [comment]
Nechapem preco sa pytate tu. Odpoved netusim takze zatvaram kedz to s archivom nic nema.
