### ISSUE TITLE
problem s iVysilani CT

### ISSUE THREAD

**Issue by nicknamed78** [mtester270/archivczskpremium#48]
Po reflashi jsem vcera obnovil zalohu archivczkskpremium (settings a zkopirovany adresar pluginu) tak, ze jsem vypnul GUI, prepsal settings, prepsal plugin adresar, zapnul gui. Pri spusteni se mne zeptal, zda chci novou verzi,coz mne trochu zmatlo, neb tu jsem tam predtim nakopiroval podle videonavodu na youtube, ale ok neb O2TV funguje bez problemu (dalsi jsem nezkousel), ale nejede iVysilani CT, pri kliknuti na nazev videa se objevila kdysi vyzva na kvalitu pripadne to rovnou prehralo v nejvyssi nebo nejhorsi kvalite podle nastaveni,ale nyni to nedela nic. Prikladam log, prosim o radu jak to vyresit. Dekuji 
[debug. archivecyskpremium.log](https://github.com/mtester270/archivczskpremium/files/4707620/debug.archivecyskpremium.log)

**Comment by mtester270** [comment]
Pokial mate zalohu poslednej verzie V6 z 5.5.2020 tak pokial to spravite podla videonavodu tak vam nemoze pytat update (medzi instalaciou a obnovenim sa pristroj nerestartuje ani nespusta archiv).

Co sa tyka iVys tak ked spustim Podle data 31.05. ct1 Zajimavosti s regiounu tak to prehrava. Testovat zvysok moc nemozem kedze maju regionalne obmedzenie na obsah.

Pokial vam ani to neprehrava tak preinstalujte a obnovte plugin.

**Comment by mtester270** [comment]
ziadna reakcia takze zatvaram.
