### ISSUE TITLE
Stream-Cinema

### ISSUE THREAD

**Issue by sustek121** [mtester270/archivczskpremium#49]
Dobrý den.Mám problém v Stream-Cinema s výběrem a přehráváním uložených(stažených souborů).Zeleným tlačítkem si zobrazím uložené soubory a když vyberu šipkami film A a potvrdím OK pro přehrávání tak se začne přehrávat třeba film C. Pokud žlutým tlačítkem změním seřazení souborů tak se viditelně nic neděje,ale zdá se,že volba "podle velikosti" vše napraví,ale tato volba není primární-po dalším spuštěni Stream-Cinema se nastaví automaticky "podle data"Mám Vaší poslední aktualizaci a přístroj VU+Zero 4K .Děkuji moc za pomoc.Šustek 
https://photos.google.com/album/AF1QipMTv_60v2CCzUplUPcLzCFm8wk2mdyg2V1eCV-G/photo/AF1QipOFlrQgg16WcMLWRMGKpg9NNXF7_gI5K3RDszIb

**Comment by mtester270** [comment]
Nikdy som to takto nepouzival. Kazdopadne pozriem ked bude cas, takze pripadny fix v dalsej verzii.

Zatial doporucim v zozname stiahnutych skor pouzivat prehliadac medii z enigma2 (stiahnute subory najdete ../movies/....stream-cinem/* pokial ste si nezmenili cestu)

**Comment by mtester270** [comment]
Ak bez toho nemozete zit a nechce sa vam cakat na dalsi update tak napiste mail poslem vam fix (bezplatne).

**Comment by sustek121** [comment]
Dobrý den.Nechci Vám přidělávat práci,klidně měsíc počkám.Děkuji moc.

---------- Původní zpráva ----------
Od: mtester270 
Datum: 17. 6. 2020 v 07:38:18
Předmět: Re: [mtester270/archivczskpremium] Stream-Cinema (#49)





Ak bez toho nemozete zit a nechce sa vam cakat na dalsi update tak napiste 
mail poslem vam fix (bezplatne).



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
(https://github.com/mtester270/archivczskpremium/issues/49#issuecomment-645162896)
, or unsubscribe

**Comment by mtester270** [comment]
Bola to prkotina je to hotove a update boh vie kedy bude dalsi, zatial tam moc uz nemam co vylepsovat pokial nikto nic neavrhne takze napiste mail ked tak ... kontakt lahko najdete cez googla :D

**Comment by Messo8080** [comment]
A kam mozeme navrhovat napady?

**Comment by mtester270** [comment]
Bud sem zalozenim noveho issue alebo mailom https://github.com/mtester270/archivczskpremium/blob/master/README.md
