### ISSUE TITLE
Trakt. TV označenie videného

### ISSUE THREAD

**Issue by gladius70** [mtester270/archivczskpremium#5]
Ahoj,
poprosím o návod na odpárovanie zariadenia. Viem, že si o tom písal na inom fóre, ale potom si ten postup vymazal. 
Patrím k tým, čo trakt spôsoboval nezobrazovanie obsahu stream cinema, tak som ho musel vypnúť. 
Chcel by som to znova rozbehnúť a nanovo spárovať, lebo hlavne pri seriáloch je to konfortné.
Ďakujem

**Comment by mtester270** [comment]
Teraz neviem co chces najskor pises ze chces odparovat potom sparovat :D.

Prihlasis sa cez telnet das 
init 4
potom pojdes cez FTP na subor /etc/enigma2/settings a upravis ho a to tak ze vymazes vsetky riadky kde je nazov *trakt*

potom znova telnet a das init 3, spustis archiv v nastaveni stream cinema zapnes trakt a v hlavnej ponuke SC prejdes na polozku trakt ci tak nejak sa to vola a vyhodi ti okno s linkou
