### ISSUE TITLE
StreamCinema2.0

### ISSUE THREAD

**Issue by Messo8080** [mtester270/archivczskpremium#51]
Najprv chcem ocenit tvoju pracu, a musim uznat, ze Archiv je perfektne spracovany. Pouziva sa vyrazne lepsie ako free edicia, zda sa mi logickejsi.

A preto sa chcem spytat, ci je nejaka moznost ze si si rozmyslel a spravis doplnok aj pre StreamCinema2? Teraz ked si spominal ze je viac menej vsetko opravene a dokoncene. Staci len odpoved ci je sanca, ze raz bude. Neviem ako je to s API do DB, ale verim, ze s chalanmi sa da dohodnut. 

Ja v podstate pouzivam tvoj E2 extension len kvoli SC2. STB dostal zrazu iny rozmer a stahovat si filmy medzi nahravky je top.

**Comment by mtester270** [comment]
SC2 nebude nikdy. 
Dovod je jednoduchy: autori SC2 ukradli data a este k tomu su taki drzi ze ukradli aj nazov doplnku akurat tam pridali 2.0. Proste prizivnici a ja ich teda podporovat nemienim.

Ale tak comu sa cudovat v tychto nasich statikoch: 

> **Co neukradnes to nemas!**
