### ISSUE TITLE
SC sekání

### ISSUE THREAD

**Issue by L0th4r** [mtester270/archivczskpremium#52]
Čago, v posledních dnech se hodně filmů seká i na nejmenší kvalitu. Mám poslední aktualizaci a internet optiku 100/100

**Comment by mtester270** [comment]
Podla vas som prevadzkovatel akehokolvek obsahu nejakeho pluginu?
Odpoviem vam: nie niesom, takze ked vam nieco seka tak sa stazujte u toho odkial tecu data.
