### ISSUE TITLE
Přestal fungovat Stream Cinema

### ISSUE THREAD

**Issue by kubisek78** [mtester270/archivczskpremium#53]
Po aktualizaci 28.08. přestal fungovat plugin stream cinema (těsně před aktualizací fungoval). Po rozkliknuti není vůbec vidět nabídka, jen dvě tečky. Ostatní ok.

**Comment by vladonb74** [comment]
> Po uplynutí 28.08. kino s prerušeným nebezpečenstvom doplnkového prúdu (tesniace pred aktualizáciou fungoval). Po rozkliknuti nie je nikdy viditelná ponuka, jen dvě tečky. Ostatní ok.

U mna ten isty problem,mam VU+4K a kazda jedna aktualizacia prebehla bez problemou,tato posledna ale nie.

**Comment by kakomako1173** [comment]
Ahoj 28.8.2020 som aktualizoval na V09 všetko zmyzlo záložky ostali viditelné po otvorení prázdne ..používam SF8008 octagon openATV

**Comment by vladonb74** [comment]
Prikladam moj log..


17:16:01.787 [DEBUG] adding addon=VideoAddon(joj.sk-1.0.3) (plugin.video.joj.sk)
17:16:01.833 [DEBUG] adding addon=VideoAddon(Drtinova Veselovsky TV-1.0.1) (plugin.video.dvtv.cz)
17:16:01.892 [DEBUG] adding addon=VideoAddon(iPrima-1.0.2) (plugin.video.primaplay)
17:16:01.943 [DEBUG] adding addon=VideoAddon(markiza.sk-1.0.3) (plugin.video.markiza.sk)
17:16:02.015 [DEBUG] adding addon=VideoAddon(O2TV-1.2.0) (plugin.video.o2tv)
17:16:02.071 [DEBUG] adding addon=VideoAddon(Nova Plus TV Archiv-1.0.4) (plugin.video.novaplus)
17:16:02.167 [DEBUG] adding addon=VideoAddon(OrangeTV-1.1.0) (plugin.video.orangetv)
17:16:02.264 [DEBUG] adding addon=VideoAddon(SledovanieTV-1.2.1) (plugin.video.sledovanitv)
17:16:02.304 [DEBUG] adding addon=VideoAddon(rtvs.sk-1.0.5) (plugin.video.rtvs.sk)
17:16:02.347 [DEBUG] adding addon=VideoAddon(Mestska TV Ruzomberok-1.0.0) (plugin.video.mtr.sk)
17:16:02.363 [DEBUG] adding addon=ToolsAddon(stream resolver-1.0.0) (script.module.stream.resolver)
17:16:02.444 [DEBUG] adding addon=VideoAddon(Soubory Online-1.0.1) (plugin.video.online-files)
17:16:02.487 [DEBUG] adding addon=VideoAddon(TA3-1.0.3) (plugin.video.ta3.com)
17:16:02.529 [DEBUG] adding addon=VideoAddon(DigiGO-1.0.1) (plugin.video.digigo)
17:16:02.587 [DEBUG] adding addon=VideoAddon(MallTV-1.0.4) (plugin.video.malltv)
17:16:02.598 [DEBUG] adding addon=ToolsAddon(Common python modules-1.0.0) (script.module.common)
17:16:02.684 [DEBUG] adding addon=VideoAddon(Stream Cinema-1.2.2) (plugin.video.stream-cinema)
17:16:02.731 [DEBUG] adding addon=VideoAddon(TelevizeSeznam-2.0.2) (plugin.video.streamtv)
17:16:02.795 [DEBUG] adding addon=VideoAddon(Sosac-1.0.0) (plugin.video.sosac.ph)
17:16:02.857 [DEBUG] adding addon=VideoAddon(iVysilani - Ceska televize-1.0.2) (plugin.video.ivysilani)
17:16:02.860 [DEBUG] Doplnky (CZ & SK) successfully loaded
17:16:02.861 [DEBUG] initializing addons...
17:16:24.251 [INFO] Checking archivCZSK premium update...
17:16:24.937 [INFO] No new update found.
17:16:24.947 [DEBUG] ContentProvider start
17:16:26.180 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:16:26.187 [DEBUG] ContentProvider start
17:16:26.188 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:16:26.189 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:16:26.194 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:16:26.195 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:16:33.006 [DEBUG] ContentProvider stop
17:16:33.008 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:16:33.011 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:16:33.014 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:16:41.446 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:16:41.453 [DEBUG] ContentProvider start
17:16:41.455 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:16:41.456 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:16:41.460 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:16:41.461 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:16:43.362 [DEBUG] ContentProvider stop
17:16:43.364 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:16:43.367 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:16:43.369 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:18:53.372 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:18:53.378 [DEBUG] ContentProvider start
17:18:53.380 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:18:53.381 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:18:53.385 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:18:53.386 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:19:42.751 [DEBUG] ContentProvider stop
17:19:42.753 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:19:42.755 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:19:42.758 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:21:20.705 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:21:20.717 [DEBUG] ContentProvider start
17:21:20.719 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:21:20.719 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:21:20.724 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:21:20.725 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:21:22.146 [DEBUG] ContentProvider stop
17:21:22.149 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:21:22.152 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:21:22.155 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:21:22.749 [DEBUG] ContentProvider stop
17:23:07.235 [DEBUG] ContentProvider start
17:24:59.731 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:24:59.737 [DEBUG] ContentProvider start
17:24:59.739 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:24:59.740 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:24:59.744 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:24:59.745 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:25:00.565 [DEBUG] ContentProvider stop
17:25:00.568 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:00.571 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:00.574 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:25:01.208 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:25:01.214 [DEBUG] ContentProvider start
17:25:01.216 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:25:01.217 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:25:01.220 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:25:01.221 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:25:01.523 [DEBUG] Opening item '<PExit - ..>'...
17:25:01.533 [DEBUG] ContentProvider stop
17:25:01.535 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:01.537 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:01.540 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:25:01.789 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:25:01.795 [DEBUG] ContentProvider start
17:25:01.797 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:25:01.798 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:25:01.804 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:25:01.804 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:25:02.389 [DEBUG] Opening item '<PExit - ..>'...
17:25:02.399 [DEBUG] ContentProvider stop
17:25:02.401 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:02.403 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9ebc7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa8a0ee70>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:25:02.406 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:25:02.877 [DEBUG] ContentProvider stop
17:26:25.873 [DEBUG] adding addon=VideoAddon(joj.sk-1.0.3) (plugin.video.joj.sk)
17:26:25.908 [DEBUG] adding addon=VideoAddon(Drtinova Veselovsky TV-1.0.1) (plugin.video.dvtv.cz)
17:26:25.953 [DEBUG] adding addon=VideoAddon(iPrima-1.0.2) (plugin.video.primaplay)
17:26:25.995 [DEBUG] adding addon=VideoAddon(markiza.sk-1.0.3) (plugin.video.markiza.sk)
17:26:26.043 [DEBUG] adding addon=VideoAddon(O2TV-1.2.0) (plugin.video.o2tv)
17:26:26.073 [DEBUG] adding addon=VideoAddon(Nova Plus TV Archiv-1.0.4) (plugin.video.novaplus)
17:26:26.117 [DEBUG] adding addon=VideoAddon(OrangeTV-1.1.0) (plugin.video.orangetv)
17:26:26.169 [DEBUG] adding addon=VideoAddon(SledovanieTV-1.2.1) (plugin.video.sledovanitv)
17:26:26.206 [DEBUG] adding addon=VideoAddon(rtvs.sk-1.0.5) (plugin.video.rtvs.sk)
17:26:26.246 [DEBUG] adding addon=VideoAddon(Mestska TV Ruzomberok-1.0.0) (plugin.video.mtr.sk)
17:26:26.260 [DEBUG] adding addon=ToolsAddon(stream resolver-1.0.0) (script.module.stream.resolver)
17:26:26.327 [DEBUG] adding addon=VideoAddon(Soubory Online-1.0.1) (plugin.video.online-files)
17:26:26.365 [DEBUG] adding addon=VideoAddon(TA3-1.0.3) (plugin.video.ta3.com)
17:26:26.402 [DEBUG] adding addon=VideoAddon(DigiGO-1.0.1) (plugin.video.digigo)
17:26:26.443 [DEBUG] adding addon=VideoAddon(MallTV-1.0.4) (plugin.video.malltv)
17:26:26.455 [DEBUG] adding addon=ToolsAddon(Common python modules-1.0.0) (script.module.common)
17:26:26.526 [DEBUG] adding addon=VideoAddon(Stream Cinema-1.2.2) (plugin.video.stream-cinema)
17:26:26.565 [DEBUG] adding addon=VideoAddon(TelevizeSeznam-2.0.2) (plugin.video.streamtv)
17:26:26.613 [DEBUG] adding addon=VideoAddon(Sosac-1.0.0) (plugin.video.sosac.ph)
17:26:26.653 [DEBUG] adding addon=VideoAddon(iVysilani - Ceska televize-1.0.2) (plugin.video.ivysilani)
17:26:26.655 [DEBUG] Doplnky (CZ & SK) successfully loaded
17:26:26.656 [DEBUG] initializing addons...
17:30:35.698 [INFO] Checking archivCZSK premium update...
17:30:36.546 [INFO] No new update found.
17:30:36.554 [DEBUG] ContentProvider start
17:30:37.663 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:30:37.669 [DEBUG] ContentProvider start
17:30:37.671 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:30:37.671 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:30:37.675 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:30:37.676 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:30:39.057 [DEBUG] ContentProvider stop
17:30:39.059 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9e5e7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa89a9890>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:30:39.062 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9e5e7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa89a9890>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:30:39.065 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:30:42.499 [DEBUG] ContentProvider pause
17:33:33.837 [DEBUG] ContentProvider resume
17:33:34.298 [DEBUG] ContentProvider stop
17:33:39.284 [INFO] Checking archivCZSK premium update...
17:33:40.602 [INFO] No new update found.
17:33:40.610 [DEBUG] ContentProvider start
17:41:25.803 [DEBUG] ContentProvider stop
17:44:00.549 [DEBUG] ContentProvider start
17:44:04.945 [DEBUG] ContentProvider pause
17:44:57.277 [DEBUG] ContentProvider resume
17:44:57.504 [DEBUG] ContentProvider stop
17:48:01.109 [INFO] Checking archivCZSK premium update...
17:48:02.651 [INFO] No new update found.
17:48:02.662 [DEBUG] ContentProvider start
17:48:03.862 [DEBUG] Opening item '<PVideoAddon - Stream Cinema>'...
17:48:03.867 [DEBUG] ContentProvider start
17:48:03.869 [DEBUG] VideoAddon(Stream Cinema-1.2.2) adding importer
17:48:03.870 [DEBUG] VideoAddon(Stream Cinema-1.2.2) importer is not in meta_path (adding)
17:48:03.874 [DEBUG] ToolsAddon(stream resolver-1.0.0) adding importer
17:48:03.875 [DEBUG] ToolsAddon(stream resolver-1.0.0) importer is not in meta_path (adding)
17:48:05.959 [DEBUG] Opening item '<PExit - ..>'...
17:48:05.969 [DEBUG] ContentProvider stop
17:48:05.972 [DEBUG] VideoAddon(Stream Cinema-1.2.2) removing importer, META=[<six._SixMetaPathImporter object at 0xa9e5e7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa89a9890>, [plugin.video.stream-cinema-importer] , [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:48:05.975 [DEBUG] ToolsAddon(stream resolver-1.0.0) removing importer, META=[<six._SixMetaPathImporter object at 0xa9e5e7f0>, <urllib3.packages.six._SixMetaPathImporter object at 0xa89a9890>, [script.module.stream.resolver-importer] , [custom_sys-importer] ]
17:48:05.978 [DEBUG] <ArchivCZSKpContentScreen>: workingFinished
17:48:07.897 [DEBUG] ContentProvider stop

**Comment by mtester270** [comment]
Treba napisat mail, kde uvediete povodny kod, nasledne by som vam odpisal ze mate preinstalovat plugin na verziu 1.0 a nasledne poslat novy kod. Dany kod uz neplatte!!!

ps: email kontakt snad najdete ked ste boli schopni zalozit issue 👍
