### ISSUE TITLE
streamcinema community

### ISSUE THREAD

**Issue by hyllm** [mtester270/archivczskpremium#54]
why there is no streamcinema community plugin in PREMIUM and in FREE it is????

**Comment by Ciksa** [comment]
Because you didn't pay. 
Money won't make you happy, but shopping yes. :-D

**Comment by hyllm** [comment]
> Because you didn't pay and even the chicken doesn't burrow for free and you confuse concepts with impressions.
> Money won't make you happy, but shopping yes. :-D

are tou really stupid or what?

i am paying for premium, and stream cinema community is not there... on free version, thare is stream cinema community...

**Comment by Ciksa** [comment]
> are you really stupid or what?
> 
> i am paying for premium, and stream cinema community is not there... on free version, there is stream cinema community... so in this case, it's opposite... as paying user i don't have something non-paying user has...

Not me but you are stupid. If you paid for Premium, you don't need a Community with their neutered database.
If that weren't the case, you'd know that the whole "SC Comunity" project is just a "of spite" SC creator built on a stolen old version of a database from SC. But also stupidity and ignorance are gods' gifts.

**Comment by mtester270** [comment]
Nechapem tu anglictinu ked je doplnok CZ SK mas na to nejaky dovod ci si fakt zahranicny pouzivate?

English response: first reason why not is that I hate people who steal data and are so stupid to use almost same name as original addon (parasite). Second is, because for me addon is in beta version so i dont need update code every week/day and server sponsored or provided by webshare is many time death (down).

Have a nice day.

**Comment by hyllm** [comment]
No... ok... na githube som zvyknuty komunikovat v EN, takze sila zvyku. 👍 

co sa tyka prvej veci... neviem co myslim kradnutim dat... ak vies ako funguje ten povodny stream cinema... ktor presiel na kra.sk, tak to bola obycajna zlodejina, lebo autor as chcel napakovat, a cele to fungovalo na maskovani linkov webshare ako kra.sk...

ad2: nevidim dovod, aby som ako platiaci za premium, nemal mat tento plugin, pokial existuje, a pokial je dokonca obsiahnuty vo FREE verzii ArchivCZSK (co viem, ze je, kedze pouzivam Premium na hlavnom receiveri v obyvacke a free v spalni)...

**Comment by mtester270** [comment]
Nazor ti neberiem, ale podla mna sa mylis.

Premium nie je o tom ze ked si daco platis tak prijmatel platby bude tancovat ako ty piskas 😁, je o tom ze sa doplnky snazim udrzovat nic viac a teda ak dovolis tak ti zatial doporucim pouzivat aj free verziu archivu, nie je ziadny problem v spolocnom fungovani na jednom pristroji. Takze zatial ziadne comunity v premium nebude.

**Comment by hyllm** [comment]
to ja netvrdim, ze developer bude piskat... :) len je divne, ze FREE ma nieco naviac, ako PREMIUM.

**Comment by mtester270** [comment]
Nic divne na tom nie je, support robi uplne iny clovek a uz dost davno ide kazdy svojou cestou, moja cesta nie je v opakovani veci co su vo free verzii. 
Ps: piskate vy a nie developer ale asi len preklep 😁
