### ISSUE TITLE
údaje k platbě?

### ISSUE THREAD

**Issue by Ivan0390** [mtester270/archivczskpremium#6]
kde je nejdu, když jsem si je nepoznamenal a odklepl?

**Comment by mtester270** [comment]
Zobrazi pri spusteni pri spusteni archivu napr. ked restartujete zariadenie alebo kazde 2h pri spusteni (v novej verzii to je kazdych 8h). Ale v nastaveni vypne aktualizacie ulozite potom ich znova zapnete ulozite a spustite archiv nanovo.
