### ISSUE TITLE
Openatv 6.3 rozchadzanie obrazu. Dinobot 4k+

### ISSUE THREAD

**Issue by jdemovic** [mtester270/archivczskpremium#7]
Zdravim, mam trosku problem s gstreamerom a Pluginom premiu . Ked spustim film, tak sa mi po urcitom case zacne kockovat a rozchadzat obraz (po 10-20 minutach). Ak dam na chvilu pauzu a potom spustim, tak to znovu ide urcitu dobu a znovu kockovanie. Ak spustim rovnaky release cez kodi plugin, tak ide vsetko OK. Skusal som aj mensi subor koli netu, ale bezvysledne. (Speedtest 50/10).
V kodi vsetko OK v arcivczsk sekanica. Pekny den. J

**Comment by hansolo272** [comment]
nastavení doplnku premium
rtmp bufer 15000 ms
net optic cabel 50/30 test
vše ok -- ten tvuj box je typu hybrid android /arm 
a zde je možné vše -- netuším a nevíme jak je na tom
 image asi jen podpora pro openatv ale skus rtmp buf - u mne vše ok

**Comment by mtester270** [comment]
Skus iny image alebo nejak aktualizovat gstreamer ak ti teda nepomoze nastavenie buffra. S tymto ti nemam ako poradit prehravanie funguje Ok takze mozno kombinacia dinobot + atv nie je dobra. Ale pouzivaj kodi.
