### ISSUE TITLE
Inkognito JOJ plugin

### ISSUE THREAD

**Issue by mukates** [mtester270/archivczskpremium#8]
Ahoj, v plagine JOJ.SK je vo vsetkych adresaroch rovnaka cast. Inkognito-silvester-31.12.2018. Archiv premium, VU+ Solo2, VTI 14.0.3. V archive mi zobrazuje verziu JOJ.SK 1.0.0 Poplatok za update uhradeny.

**Comment by hansolo272** [comment]
v premium pouze zmena u s.cinema na 1.0.1
https://github.com/mx3L/archivczsk-doplnky/issues/29
ostatní vše na 1.0.0 
na joj skus old verzi 
z podporou mx3l 
nebo si počkej na další up premium

**Comment by mtester270** [comment]
Tu mas info za co si momentalne zaplatil treba len trosku citat https://github.com/mtester270/archivczskpremium/releases

O joj viem ale neviem ci to mam opravovat a robit dalsiu aktualizaciu. Bude ochotny zaplatit znova?

**Comment by mukates** [comment]
Ahoj, ano, viem za co som zaplatil. Precital som si to. To nebola staznost na platbu :-) Ano, pokial je mozne urobit opravu doplnku, samozrejme zaplatim. V tom nevidim ziaden problem. Za pracu sa predsa plati...

**Comment by mtester270** [comment]
Ok, do konca tyzdna bude. Este tam chcem cosi prihodit aby to nebola len jojka.
