### ISSUE TITLE
Na co je viazana platba

### ISSUE THREAD

**Issue by jdemovic** [mtester270/archivczskpremium#9]
Ahoj,
uhradil som premium a nasledne dal iny image koli kockovaniu obrazu. Teraz ked som instaloval  znovu plugin, tak mi zobrazilo udaje o platbe s inym kodom. Je aktualizacia prenosna v ramci jedneho prijimaca ? Alebo po zmene image je potrebne znovu uhradit poplatok s inym kodom.
Dakujem
J

**Comment by mtester270** [comment]
Je prenosna len si to z image v ktorom si to uz aktualizoval staci prekopirovat. Mozno v tom image kde to prekopirujes bude na za iatku hlasit ze zaplatte ale to bud pockas 14dni alebo v /etc/enigma2/settings vymazes riadok kde je ten kod.

**Comment by jdemovic** [comment]
Ahoj,
a co vsetko treba prekopirovat ?
Dakujem.
J

**Comment by mtester270** [comment]
zlozku /usr/lib/enigma2/python/Plugins/Extensions/archivCZSKpremium/

v image do ktoreho to ides kopirovat by si uz mal mat naistalovany archiv premium inac ti to nepojde lebo sa tam kopiruju veci pri instalacii. Pokial ho tam nemas tak bud cez IPK alebo cez stary archiv daj prechod na premium.
